# Source: jenkins-resources/templates/tekton-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-tekton-pipelines
  annotations:
    meta.helm.sh/release-name: 'jenkins-resources'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get
      - watch
