apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: sagarshrestha24
    provider: https://github.com
    providerKind: github
    repositories:
    - name: akscicd
    - name: jenkins-pipeline-examples
    - name: nodeapp1
    - name: nodeapp2
    scheduler: in-repo
  jenkinsServers:
  - groups:
    - owner: sagarshrestha24
      provider: https://github.com
      providerKind: github
      repositories:
      - name: jenkins-pipeline-examples
    server: myjenkins
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
